<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7</TargetFrameworks>
    <RootNamespace>WebSocketSharp</RootNamespace>
    <Copyright>sta.blockhead</Copyright>
    <Version>2.2.0</Version>
    <AssemblyVersion>2.2.0</AssemblyVersion>
    <PackageVersion>2.2.0</PackageVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Description>A C# implementation of the WebSocket protocol client and server</Description>
    <BaseOutputPath>..\..\bin\WebSocketSharp\</BaseOutputPath>
  </PropertyGroup>

</Project>
