<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net7</TargetFrameworks>
    <RootNamespace>OBSWebsocketDotNet</RootNamespace>
    <Copyright>Copyright © Stéphane Lepin 2020</Copyright>
    <Version>5.3.0</Version>
    <PackageVersion>5.3.0</PackageVersion>
    <AssemblyVersion>5.3.0</AssemblyVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <BaseOutputPath>..\..\bin\ObsWebsocket\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebSocketSharp\websocket-netcore.csproj" />
  </ItemGroup>

</Project>
